### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by MUA-218** [harfang3d/dogfight-sandbox-hg1#12]
Can't run game showing this error.
C:\Users\AKML\PycharmProjects\pythonProject11\venv\Scripts\source>main.py
Traceback (most recent call last):
  File "C:\Users\AKML\PycharmProjects\pythonProject11\venv\Scripts\source\main.py", line 13, in <module>
    import harfang as hg
ModuleNotFoundError: No module named 'harfang'

**Comment by astrofra** [comment]
Hi.
Have you installed the HARFANG wheel, beforehand ?
`pip install harfang`

What OS are you working on ?
'hope this helps.

**Comment by MUA-218** [comment]
how to open harfang game engine to make my own game

**Comment by astrofra** [comment]
> yes I already install harfang.
it seems that you have several installs of Python on your machine.

> how to open harfang game engine to make my own game
What do you mean by "open" ? Would you need a 3D editor ?

**Comment by MUA-218** [comment]
> > yes I already install harfang.
> 
> it seems that you have several installs of Python on your machine.
> 
> > how to open harfang game engine to make my own game
> 
> What do you mean by "open" ? Would you need a 3D editor ?
I want to make my own game with harfang3d engine

**Comment by astrofra** [comment]
Please note this project is not maintained anymore as it was replaced by a new version that can be found here:
https://github.com/harfang3d/dogfight-sandbox-hg2

If you have any question, feel free to contact us on contact@harfang3d.com
