### ISSUE TITLE
what are the keyboard controls? 

### ISSUE THREAD

**Issue by Aashmans** [harfang3d/dogfight-sandbox-hg1#13]

**Comment by ErkMkd** [comment]
Hi !
You can see the keyboard controls at main menu:
![image](https://user-images.githubusercontent.com/11889393/125826478-6fb28fd3-b686-4a3b-a852-beb96f124b2b.png)

I hope my answer will be useful to you!

Sincerely,
Eric.

**Comment by astrofra** [comment]
Hi, thanks for your interest!
Please note this project is not maintained anymore as it was replaced by a new version that can be found here:
https://github.com/harfang3d/dogfight-sandbox-hg2

If you have any question, feel free to contact us on contact@harfang3d.com
