### ISSUE TITLE
EROOR

### ISSUE THREAD

**Issue by muzhizhao** [harfang3d/dogfight-sandbox-hg1#14]
Traceback (most recent call last):
  File "E:\game-dogfight-master\source\main.py", line 15, in <module>
    from SeaRender import *
  File "E:\game-dogfight-master\source\SeaRender.py", line 15, in <module>
    from data_converter import *
  File "E:\game-dogfight-master\source\data_converter.py", line 26, in <module>
    def vec2_to_list(v: hg.Vector2):
AttributeError: module 'harfang' has no attribute 'Vector2'

I have a problem with compiling after downloading

**Comment by muzhizhao** [comment]
window 10 python3.8  harfang 2.0.111

**Comment by astrofra** [comment]
Hi.
The version of HARFANG you installed it too recent.
If you want to try this Dogfight, you should use the previous HARFANG 1.2.0 version : 
https://pypi.org/project/harfang/1.2.0/

Please refer to the requirements.txt.

**Comment by muzhizhao** [comment]
Thank you, my problem is solved. Currently I need to port this software to the flight joystick. Do you have any recommendations?

**Comment by astrofra** [comment]
We use a Logitech Attack 3 stick.
Any USB-compatible Stick should help.
