### ISSUE TITLE
Get error in window 10 python3.7 harfang 1.2.0

### ISSUE THREAD

**Issue by Wan-xiaohui** [harfang3d/dogfight-sandbox-hg1#15]
I have a problem during model training:
Harfang core has crashed! Version: 1.2.0, build SHA: 1538b3acd3c9351b7b9108742a5f352c98b7845d

but, I do not know where Harfang went wrong

**Comment by astrofra** [comment]
Hi, thanks for your interest!
Unfortunately, this project is not maintained anymore as it was replaced by a new version that can be found here:
https://github.com/harfang3d/dogfight-sandbox-hg2

If you have any question, feel free to contact us on contact@harfang3d.com
