### ISSUE TITLE
I can't use gan! whether I press keyEnter or not.

### ISSUE THREAD

**Issue by TUY3** [harfang3d/dogfight-sandbox-hg1#16]
Maybe my wrong operation, I can't fire the gun. I can see enemy's bullets, but I can't see mine.

**Comment by ErkMkd** [comment]
Have you tried the ENTER key on the numeric keypad ?

**Comment by TUY3** [comment]
Thanks!It's useful to use the ENTER key on the numeric keypad

**Comment by ErkMkd** [comment]
Dogfight 1 is obsolete, you can try V2 : https://github.com/harfang3d/dogfight-sandbox-hg2

**Comment by astrofra** [comment]
Hi, thanks for your interest!
As mentioned by Eric, this project is not maintained anymore as it was replaced by a new version that can be found here:
https://github.com/harfang3d/dogfight-sandbox-hg2

If you have any question, feel free to contact us on contact@harfang3d.com
