### ISSUE TITLE
What can i do to speed it up? 

### ISSUE THREAD

**Issue by TUY3** [harfang3d/dogfight-sandbox-hg1#17]
Hello, I want to change the game to a RL env. I can't get enough samples quickly ,if i don't do anything. How can i do ?

**Comment by astrofra** [comment]
Hi,
this project is not maintained anymore as it was replaced by a new version that can be found here: 
https://github.com/harfang3d/dogfight-sandbox-hg2

The new version brings several features, including the ability to run in **renderless** mode, hence allowing the simulation to run ~100 times faster.

**Comment by astrofra** [comment]
If you have any question, feel free to contact us on contact@harfang3d.com
