### ISSUE TITLE
Very Bad lag at 100% power

### ISSUE THREAD

**Issue by cdiener1** [harfang3d/dogfight-sandbox-hg1#4]
Is there anything I can do to fix that lag? When I turn down the speed to 75% it is better. Could I change the code to start at 70% power? Where would I find that variable? I heard something about autopilot. How do I do that? Is there a way to make to missiles track the enemy? Finally, what is the thing in the bottom left corner? Am I on it? Is my enemy on it? P.S. Is there a use for the aircraft carrier other then to take off from? Thanks!

**Comment by ErkMkd** [comment]
Hi,
To start at 70% thrust, just enter 0.7 here:  
https://github.com/harfang3d/game-dogfight/blob/master/source/main.py#L1208

And comment this line:  
https://github.com/harfang3d/game-dogfight/blob/master/source/main.py#L1210

Autopilot is only for IA usage. The is a ImGui debug window to test autpilot, but it's only a debug feature.  

To make missile track the enemy, you must lock your target: press "t" key. Target datas will appear in upper left corner of your screen. Then, wait for "missile lock" signal when enemy is behind you.

The thing in the bottom left corner is your radar.  
* enemies appears in red, and green when target locked.  
* Allies appears in green, and you are the plot in center.    

Note that DogFight is only a demo to show HARFANG3D possibilities. It's not a finalized game.

I hope I help you !

**Comment by StepLogic** [comment]
Erm...is it possible load .obj files instead of .geo files...?Any help will be appreciated

**Comment by astrofra** [comment]
Hi, thanks for your interest!
Please note this project is not maintained anymore as it was replaced by a new version that can be found here:
https://github.com/harfang3d/dogfight-sandbox-hg2

If you have any question, feel free to contact us on contact@harfang3d.com
