### ISSUE TITLE
Get error in ubuntu 18 and python 3.6

### ISSUE THREAD

**Issue by tgfred** [harfang3d/dogfight-sandbox-hg1#5]
`Traceback (most recent call last):
  File "/home/fred/Github/game-dogfight/source/main.py", line 13, in <module>
    import harfang as hg
  File "/home/fred/.local/lib/python3.6/site-packages/harfang/__init__.py", line 1, in <module>
    from .harfang import *
ImportError: libpython3.5m.so.1.0: cannot open shared object file: No such file or directory
`
Is it only compatible python 3.5?

**Comment by muraatozbek** [comment]
Have you solved it?

**Comment by astrofra** [comment]
Hi, thanks for your interest!
Please note this project is not maintained anymore as it was replaced by a new version that can be found here:
https://github.com/harfang3d/dogfight-sandbox-hg2

If you have any question, feel free to contact us on contact@harfang3d.com
