### ISSUE TITLE
Oh, Memory leak！！！

### ISSUE THREAD

**Issue by BlackDeal** [harfang3d/dogfight-sandbox-hg1#7]
I found that when I repeatedly pressed the backspace key to restart the game, the memory was increasing. I tried to release the memory actively, but it didn't work.

info:
Windows-7-6.1.7601-SP1
 Python ： [3.6.9]

**Comment by astrofra** [comment]
Hi, thanks for your interest!
Please note this project is not maintained anymore as it was replaced by a new version that can be found here:
https://github.com/harfang3d/dogfight-sandbox-hg2

If you have any question, feel free to contact us on contact@harfang3d.com
