### ISSUE TITLE
Does the program support many-to-many air combat？Can aircraft be modified  or defined？

### ISSUE THREAD

**Issue by Jiang1206** [harfang3d/dogfight-sandbox-hg1#8]
Does the program support many-to-many air combat？Can aircraft be modified  or defined？

**Comment by astrofra** [comment]
Hi!
The multi-combat option is on the roadmap. We will keep you posted as soon as it's available.

**Comment by astrofra** [comment]
Hi.
Please note this project is not maintained anymore as it was replaced by a new version that can be found here:
https://github.com/harfang3d/dogfight-sandbox-hg2

If you have any question, feel free to contact us on contact@harfang3d.com
